spring:
  profiles:
    active: dev
    group:
      dev: "dev"
      prod: "prod"
    include:
      - infra

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
