# 프로그램 실행 시 테이블 update
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

# 로깅 설정
logging:
  level:
    org:
      springframework:
        security: trace
        web: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: trace

SECRET_KEY_1: ${SECRET_KEY_1}
SECRET_KEY_2: ${SECRET_KEY_2}
SECRET_KEY_3: ${SECRET_KEY_3}

# 매칭 Password
MATCHING_PASSWORD : ${MATCHING_PASSWORD}
