version: '3'
services:
  animal-meeting-app:
    image: animal-meeting-app:latest
    container_name: animal-meeting-container
    networks:
      - pricewagon-network
    ports:
      - "8000:8000"
    build:
      context: .
networks:
  pricewagon-network:
    external: true  # 이미 존재하는 네트워크를 사용
