# Workflow의 이름을 지정합니다.
name: CI/CD - Phone Server

on:
  push:
    # main branch에 push(merge)될 경우 실행됩니다.
    branches: [ "cicd" ]

permissions:
  contents: read

jobs:
  build:
    environment: DEV
    # build를 진행할 운영체제를 선택합니다.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          touch ./application-prod.yml
          echo "$APPLICATION_PROD" > ./application-prod.yml
          echo "$APPLICATION" > ./application.yml
        env:
          APPLICATION_PROD: ${{ secrets.APPLICATION_PROD }}
          APPLICATION: ${{ secrets.APPLICATION }}
        shell: bash

#      - name: Gradle 권한 부여
#        run: chmod +x gradlew
#
#      - name: Gradle로 빌드 실행
#        run: ./gradlew bootjar

#      #프로젝트 zip파일로 압축
#      - name: Make Zip File
#        run: |
#          chmod +x ./scripts/deploy_phone.sh
#          zip -qq -r ./animal-meeting-app-phone.zip .
#
#        shell: bash

#      # AWS에 연결해줍니다.
#      - name: AWS 연결
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#
#      # S3에 프로젝트를 업로드 합니다.
#      - name: S3에 프로젝트 업로드
#        run: |
#          aws s3 cp \
#          --region ap-northeast-2 \
#          ./animal-meeting-app-phone.zip s3://animal-meeting-bucket

      - name: Create deploy script on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LOCAL_SERVER_HOST }}
          port: 4859
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH 개인 키의 내용
          password: ${{ secrets.LOCAL_SERVER_SSH_PASSWORD }}
          script: |
            chmod +x ~/deploy_phone.sh  # 실행 권한을 부여합니다.

#      - name: Deploy to Local Server
#        uses: appleboy/ssh-action@master
#        with:
#            host: ${{ secrets.LOCAL_SERVER_HOST }}
#            port: 4859
#            username: ${{ secrets.LOCAL_SERVER_USER }}
#            key : ${{ secrets.LOCAL_SSH_PRIVATE_KEY}}
#            password: ${{ secrets.LOCAL_SERVER_SSH_PASSWORD }}
#            source: ./scripts/deploy_phone.sh  # 로컬에서 복사할 스크립트 파일 경로
#            target: ~/deploy_phone.sh
#            script: |
#              ~/deploy_phone.sh
